// dietapp/frontend-react/src/components/Landing.jsx
import React, {useEffect, useState} from "react";
import landing from "./assets/landing.jpg"
import scary from "./assets/scary.png"
import goodjob from "./assets/goodjob.png"
import me from "./assets/me.jpg"
import myapp from "./assets/myapp.jpeg"
import "./assets/wickedcss.min.css"
import {getLastWeights, getFirstWeights} from "./Services/HttpService";
import {isLogged} from "./Services/LoggedService";

export default function Landing() {
    const [firstWeight, setFirstWeight] = useState([0])
    const [lastWeight, setLastWeight] = useState([0])
    const [logged, setLogged] = useState(false)

    useEffect(() => {
        if (isLogged()) {
            setLogged(true)
            getFirstWeights().then(response => {
                console.log(response.data)
                setFirstWeight(response.data)
            })
            getLastWeights().then(response => {
                console.log(response.data)
                setLastWeight(response.data)
            })
        }
    }, [0])

    const stateOfWeight = () => {
        if (firstWeight[0] < lastWeight[0]) {
            return "gain"
        } else if (firstWeight[0] > lastWeight[0]) {
            return "loss"
        }
        return "equal"
    }
    const weightGainOrLoss = () => {
        if (firstWeight[0] > lastWeight[0]) {
            let weightToRound = firstWeight[0] - lastWeight[0]
            return Math.round(weightToRound * 100)/100
        }
        let weightToRound = lastWeight[0] - firstWeight[0]
        return Math.round(weightToRound * 100)/100
    }


    return (
        <div>
            <div className="columns">
                <div className="column hero has-background-primary is-fullheight-with-navbar">
                    <div className="hero-body has-text-centered">
                        <div className="container is-fluid">
                            <div>
                                <div className="mt-0">
                                    <h1 className="has-text-white is-text is-size-2-mobile is-size-1 is-family-monospace has-text-weight-bold">
                                        Dietapp
                                    </h1>
                                </div>
                            </div>
                            <h2 className="is-text is-size-2-mobile is-size-2">
                                Where you can track your progress
                            </h2>
                            <div className="mt-6">
                                {logged ? <div className="columns box m-4">
                                        <div className="column is-half box has-background-grey-light">
                                            <h2 className="subtitle is-size-4 ">
                                                You started with: {firstWeight} kg<br/>
                                                Now you have: {lastWeight} kg
                                            </h2>
                                        </div>
                                        <div className="column is-half">
                                            {stateOfWeight() == "gain" &&
                                                <div className="has-text-centered">
                                                    <img src={scary}
                                                         className="rotateIn image is-128x128 is-inline-block"/>
                                                    <div className="box has-background-danger">
                                                        <h1 className="is-size-4 has-background-grey-lighter">You have
                                                            gain {weightGainOrLoss()} kg
                                                        </h1>
                                                    </div>
                                                    <p></p>
                                                </div>
                                            }
                                            {stateOfWeight() == "loss" &&
                                                <div className="has-text-centered">
                                                    <img src={goodjob}
                                                         className="slideDown image is-128x128 is-inline-block"/><br/>
                                                    <div className="box has-background-success">
                                                        <h1 className="is-size-4 has-background-grey-lighter">You have
                                                            lost {weightGainOrLoss()} kg
                                                        </h1>
                                                    </div>
                                                </div>
                                            }
                                            {stateOfWeight() == "equal" &&
                                                <div className="has-text-centered">
                                                    <img src={me}
                                                         className="zoomer image is-128x128 is-inline-block"/><br/>
                                                    <div className="box has-background-grey">
                                                        <h1 className="is-size-4 has-background-grey-lighter">You have the
                                                            same
                                                            weigth
                                                        </h1>
                                                    </div>
                                                </div>
                                            }
                                            <br/>
                                        </div>
                                    </div>
                                    :
                                    <div className="box has-background-white-bis">
                                        <img src={myapp} className="is-bordered"/>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div className="column has-background-primary hero is-fullheight-with-navbar is-hidden-mobile">
                    <div className="hero-body card-image">
                        <img src={landing} className="hero-body "/>
                    </div>
                </div>
            </div>
        </div>
    )
}

// dietapp/frontend/src/app/landing/landing.component.ts
import { Component, OnInit } from '@angular/core';
import {IsLoggedService} from "../services/is-logged.service";
import {UserService} from "../services/user.service";

@Component({
  selector: 'app-landing',
  templateUrl: './landing.component.html',
  styleUrls: ['./landing.component.css']
})
export class LandingComponent implements OnInit {
  firstWeight = [0]
  lastWeight = [0]
  logged = false

  constructor( private isloggedservice:IsLoggedService, private http:UserService) { }

  ngOnInit(): void {
    if(this.isloggedservice.theItem){
      console.log(this.isloggedservice.theItem)
      this.logged=true
      this.http.getFirstWeights().subscribe(response => {
        this.firstWeight=response
      })
      this.http.getLastWeights().subscribe(response => {
        this.lastWeight=response
      })
    }
  }

  stateOfWeight(){
    if (this.firstWeight[0] < this.lastWeight[0]) {
      return 'gain'
    } else if (this.firstWeight[0] > this.lastWeight[0]) {
      return 'loss'
    }
    return 'equal'
  }

  weightGainOrLoss(){
    if (this.firstWeight[0] > this.lastWeight[0]) {
      return this.firstWeight[0] - this.lastWeight[0]
    }
    return this.lastWeight[0] - this.firstWeight[0]
  }

}

<!--<img src="https://cdn.pixabay.com/photo/2014/07/28/11/18/scale-403585_960_720.jpg">-->
<div>
  <div class="columns">
    <div class="column hero has-background-primary is-fullheight-with-navbar ">
      <div class="hero-body has-text-centered">
        <div>
          <div>
            <div class="mt-0">
              <h1 class="is-text  is-size-1 is-family-monospace has-text-weight-bold has-text-white">
                Dietapp
              </h1><br/>
              <h2 class="is-text is-size-2-mobile is-size-2" i18n>
                Where you can track you progress
              </h2>
            </div>
          </div>
          <div class="mt-6 ">
          <div *ngIf="logged" class="columns box m-4">
            <div class="column is-half box has-background-grey-light">
              <h2 class="subtitle is-size-4 " i18n>
                At first your weight was: {{firstWeight}} kg<br/>
                Actual weight: {{lastWeight}} kg
              </h2>
            </div>
            <div class="column is-half">
              <div *ngIf="stateOfWeight() == 'gain'">
                <div class="has-text-centered">
                  <img src="./assets/scary.png" class="rotateIn image is-128x128 is-inline-block"/>
                  <h1 class="is-size-4 box has-background-danger" i18n>You have
                    gain {{weightGainOrLoss()| number: '1.1-1'}} kg</h1>
                  <p></p>
                </div>
              </div>
              <div *ngIf=" stateOfWeight() == 'loss'">
                <div class="has-text-centered">
                  <img src="./assets/goodjob.png" class="slideDown image is-128x128 is-inline-block"/><br/>
                  <h1 class="is-size-4 box has-background-success" i18n>You have loss {{weightGainOrLoss()| number: '1.1-1'}} kg</h1>
                </div>
              </div>
              <div *ngIf=" stateOfWeight() == 'equal'">
                <div class="has-text-centered">
                  <img src="./assets/me.jpg" class="zoomer image is-128x128 is-inline-block"/><br/>
                  <h1 class="is-size-4 box has-background-grey" i18n>You have the same weigth</h1>
                </div>
              </div>
              <br/>
            </div>
          </div>
          <div *ngIf="!logged">
            <div class="box has-background-white-bis">
              <img src="./assets/myapp.jpeg" class="is-bordered"/>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="column has-background-primary hero is-fullheight-with-navbar is-hidden-mobile">
      <div class="hero-body card-image">
        <img src="./assets/landing.jpg" />
      </div>
    </div>
  </div>
</div>
