// dietapp/frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup, Validators } from "@angular/forms";
import {Router} from "@angular/router";
import {AuthService} from "../services/auth.service";
import { IsLoggedService } from '../services/is-logged.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  submitted = false;
  errorMessage = '';
  isLoggedin = false;
  isLoginFailed = false;
  constructor(private authHttp:AuthService, private router: Router , private islogged:IsLoggedService) { }

  ngOnInit(): void {
    if(this.islogged.theItem){
      this.router.navigate(['/'])
    }
    this.loginForm = new FormGroup({
      name: new FormControl('', Validators.required),
      password: new FormControl('', Validators.required),
      });
  }

  onSubmit(){
    if(this.loginForm.valid){
      this.submitted = true;
      this.authHttp.login(this.loginForm.value.name, this.loginForm.value.password).subscribe(
        data=>{
          this.isLoggedin = true
          this.router.navigate(['/weight-history']);
        },
        error=>{
          console.log(error);
          this.errorMessage = error;
          this.isLoggedin = false;
          this.isLoginFailed = true;
        }
      )
    }
  }

}

<div class="hero is-primary is-fullheight-with-navbar">
  <div class="hero-body is-justify-content-center is-align-items-center">
    <div class="columns is-flex is-flex-direction-column box">
      <div class="column">
        <form class="form" [formGroup]="loginForm" (ngSubmit)="onSubmit()">
          <div class="field">
            <label class="label" i18n>Email</label>
            <input formControlName="name" class="input"/>
            <div *ngIf="loginForm.controls['name'].errors && loginForm.controls['name'].touched" class="help is-danger">
              <p *ngIf="loginForm.controls['name'].errors['required']" i18n>required</p>
            </div>
          </div>
          <div class="field">
            <label class="label" i18n>Password</label>
            <input formControlName="password" type="password" class="input"/>
            <div *ngIf="loginForm.controls['password'].errors && loginForm.controls['password'].touched" class="help is-danger">
            <p *ngIf="loginForm.controls['password'].errors['required']" i18n>required</p>
          </div>
            <p class="help is-danger" *ngIf="errorMessage" i18n>username or password are incorrect</p>

          </div>
          <button type="submit" class="button is-primary is-fullwidth" i18n>login</button>
        </form>
      </div>
    </div>
  </div>
</div>

// dietapp/frontend-react/src/components/Login.jsx
import React, {useEffect, useState} from "react";
import {login} from "./Services/HttpService";
import {useNavigate} from "react-router-dom";

export default function Login() {
    const navigate=useNavigate()
useEffect( () => {
    if(localStorage.key('username')){
            navigate('/')
    }
    },
)
    const [error, setError] = useState('')
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')

    const handleSubmit = (event) => {
        event.preventDefault();
        login(username, password).then(resp => {
            if(resp){
                localStorage.setItem('username', resp.data.userName)
                localStorage.setItem('roles', resp.data.roles)
                navigate('/weighthistory')

            }
        }).catch(function (error){
            if(error.response.status === 401){
                setError('Username or Password are incorrect')
            }
        })

    };

    const handleChange = (event) => {
            if(event.target.name === 'username'){
                setUsername(event.target.value)
            }else if(event.target.name === 'password'){
                setPassword(event.target.value)
            }
    }

    return(
        <div className="hero is-primary is-fullheight-with-navbar">
            <div className="hero-body is-justify-content-center is-align-items-center">
                <div className="columns is-flex is-flex-direction-column box">
                    {error && <h2 className="help is-danger">{error}</h2>}
                    <div className="column">
                        <form onSubmit={handleSubmit} className="form">
                            <div className="field">
                                <label className="label">Username</label>
                                <input type="text" className="input" name="username" required onChange={handleChange}/>
                            </div>
                            <div className="field">
                                <label className="label">Password</label>
                                <input className="input" type="password" name="password" required
                                       onChange={handleChange}/>
                            </div>
                            <div>
                            </div>
                            <div>
                                <button className="button is-primary is-fullwidth" type="submit">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
}
