// dietapp/frontend/src/app/weight-history/weight-history.component.ts
import {Component, ElementRef, OnDestroy, OnInit} from '@angular/core';
import {UserService} from "../services/user.service";
import {Weight} from "../models/weight.model";
import {last, Observable} from "rxjs";
import {Router} from "@angular/router";

@Component({
  selector: 'app-weight-history',
  templateUrl: './weight-history.component.html',
  styleUrls: ['./weight-history.component.css']
})
export class WeightHistoryComponent implements OnInit  {
  modalAdd=false;
  modalOpen=false;
  weightForSent:Weight|null=null;
  weights: Weight[]= [];
  dateWeights!:Date[];
  constructor(private http: UserService, private el:ElementRef, private router:Router) {
    this.http.getWeightHistory()
      .subscribe(weight => this.weights = weight);
  }

  ngOnInit(): void {
  }

  obtainWeights(){
    this.http.getWeightHistory()
      .subscribe(weight => this.weights = weight);
  }

  AddOpenOrClose(){
    this.weightForSent=null;
    this.modalAdd=!this.modalAdd;
  }

  openWeight(weight:Weight){
    this.weightForSent=weight;
    this.modalAdd=!this.modalAdd;
  }
  closeWeight(){
    this.modalOpen=!this.modalOpen;
  }
  refresh(){
    this.http.getWeightHistory()
      .subscribe(weight => this.weights = weight);
  }


}

<div  class="has-background-primary is-fullheight-with-navbar">
  <div  class="container is-max-widescreen is-centered has-background-white-bis p-5">
    <app-add-weight (close)="AddOpenOrClose()" (refresh)="refresh()" *ngIf="modalAdd"
                    [weight]="weightForSent"></app-add-weight>
    <button (click)="AddOpenOrClose()" class="button is-primary mb-5" i18n>Add Weight</button>
    <div class="has-background-white box">
      <h1 class="has-text-centered is-size-4" i18n>Your weight graph</h1>
      <app-chart-weight [weights]="weights"></app-chart-weight>
    </div>
    <div class="columns">
      <div class="column is-centered">
        <div *ngFor="let weight of weights">
          <div (click)="openWeight(weight)" class="box mb-2 p-1 has-text">
            <h3 class="m-1">{{weight.date.toString().split('T')[0]}}</h3>
            <h2 class="m-1">{{weight.weight| number: '1.1-1'}} kg.</h2>
          </div>
        </div>
        <h1 class="has-text-centered m-3 is-size-3">Table</h1>
      <table class="table is-fullwidth is-scrollable">
        <thead>
        <tr>
          <th i18n>Date</th>
          <th i18n>Weight</th>
        </tr>
        </thead>
        <tbody height="200px">
        <ng-container *ngFor="let weight of weights">
          <tr>
            <th>{{weight.date.toString().split('T')[0]}}</th>
            <th>{{weight.weight| number: '1.1-1'}}</th>
          </tr>
        </ng-container>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

// dietapp/frontend-react/src/components/WeightHistory/WeightHistory.jsx
import React, {useEffect, useState} from "react";
import {getWeights} from "../Services/HttpService";
import ItemWeight from "./ItemWeight";
import ModalAddOrEdit from "./ModalAddOrEdit";
import ChartWeight from "./ChartWeight";

export default function WeightHistory() {
    const [open, setOpen] = useState(false);
    const [weights, setWeights] = useState([])
    const [refresh, setRefresh] = useState(true)
    const [weightToModal, setWeightToModal] = useState({id: -1, weight: '', date: null})

    const handleOpen = () => {
        setOpen(true)
    }
    const handleClose = () => {
        setWeightToModal({id: -1, weight: '', date: null})
        setOpen(false)
    }

    useEffect(() => {
        getWeights().then(
            resp => {
                setWeights(resp.data)
            }
        )
    }, [refresh])
    const edit = ({id, weight, date}) => {
        setWeightToModal({id: id, weight: weight, date: date});
        handleOpen()
    }
    let drawItems = weights.map((w) => <ItemWeight key={w.id} id={w.id} date={w.date.toString().split('T')[0]}
                                                   weight={w.weight} edit={edit}/>)
    let drawTable = weights.map((w) =>
        <tr key={w.id}>
            <th>{w.date.toString().split('T')[0]}</th>
            <th>{w.weight}</th>
        </tr>
    )
    const handleRefresh = () => {
        setRefresh(!refresh)
    }


    return (
        <div className="has-background-primary is-fullheight-with-navbar">
            <div className="container is-max-widescreen is-centered has-background-white-bis p-5">
                <button onClick={handleOpen} className="button is-primary mb-5">Add Weight</button>
                <div className="has-background-white box">
                    <h1 className="has-text-centered is-size-4">Your weight graph</h1>
                    {weights.length > 0 && <ChartWeight weights={weights}/>}
                </div>
                {open && <ModalAddOrEdit weight={weightToModal} handleRefresh={handleRefresh}
                                         handleOpenOrClose={handleClose}/>}
                <div className="columns">
                    <div className="column is-centered">
                        <ul>
                            {drawItems}
                        </ul>
                    </div>
                </div>
                <h1 className="has-text-centered m-3 is-size-3">Table</h1>
                <table className="table is-fullwidth is-scrollable">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Weight</th>
                    </tr>
                    </thead>
                    <tbody height="200px">
                    {drawTable}
                    </tbody>
                </table>
            </div>
        </div>
    )
}
