// dietapp/frontend-react/src/App.jsx
import './App.css';
import React, {useEffect, useState} from "react";
import {Link, useNavigate} from "react-router-dom";
import {logout} from "./components/Services/HttpService";
import 'bulma/css/bulma.min.css';
import 'react-toastify/dist/ReactToastify.css'
import 'react-toastify/dist/ReactToastify.css'

export default function App() {
        const navigate = useNavigate();
        const [isLogged, setIsLogged]=useState(false)
        const clickHandler = () => {
                toggleDropdown()
                logout()
                navigate('/login')
        }
        useEffect(() => {
                if(localStorage.getItem('username')!= null){
                        setIsLogged(true)
                }else{
                        setIsLogged(false)
                }
        },[])
        function toggleDropdown() {
                const myNav = document.querySelector("#my-nav")
                const burger = document.querySelector("#burger")
                myNav.classList.toggle("is-active")
                burger.classList.toggle("is-active")
        }
        return (
            <div>
            <nav className="navbar is-light" role="navigation" aria-label="main navigation">
                    <div className="navbar-brand">
                            <Link to="/" className="navbar-item pb-0 pt-0 mt-0 ">
                                    <h1 style={{color:"#00d1b2"}} className="has-text-weight-bold is-size-3 mb-1">:</h1>
                                    <h1 style={{color:"#00d1b2"}} className="has-text-weight-bold is-size-4">D</h1>
                                    <h1 className="is-size-4"> ietapp</h1>
                            </Link>
                            <button id="burger" className="navbar-burger" onClick={toggleDropdown} aria-label="menu" aria-expanded="false"
                               data-target="my-nav">
                                    <span aria-hidden="true"></span>
                                    <span aria-hidden="true"></span>
                                    <span aria-hidden="true"></span>
                            </button>
                    </div>

                    <div id="my-nav" className="navbar-menu">
                            <div className="navbar-start">
                                    <Link to="/" className="navbar-item" onClick={toggleDropdown}>
                                            Home
                                    </Link>
                                    {isLogged && <Link to="/weight-history" className="navbar-item" onClick={toggleDropdown}>
                                            Weight History
                                    </Link>}

                            </div>

                            <div className="navbar-end">
                                    <div className="navbar-item">
                                            <div className="buttons">
                                                    {!isLogged && <Link to="/signup" className="button is-primary" onClick={toggleDropdown}>
                                                            <strong>Sign up</strong>
                                                    </Link>}
                                                    {!isLogged && <Link to="/login" className="button has-background-grey-lighter" onClick={toggleDropdown}>
                                                            Log in
                                                    </Link>}
                                                    {isLogged && <button className="button has-background-grey-lighter" onClick={clickHandler}>
                                                            Logout
                                                    </button>}
                                            </div>
                                    </div>
                            </div>
                    </div>
            </nav>
            </div>
        );
}

// dietapp/frontend/src/app/app.component.ts
import {Component, ElementRef, OnChanges, OnInit, SimpleChanges,} from '@angular/core';
import {Router} from "@angular/router";
import {AuthService} from "./services/auth.service";
import {IsLoggedService} from "./services/is-logged.service";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{
  error=false;
  login=false;
  constructor(private router:Router, private http:AuthService, private globalSrv: IsLoggedService) {
  }

  ngOnInit() {
    this.globalSrv.itemValue.subscribe((nextValue) => {
           if(nextValue!=null){
             this.login=true;
           }else{
             this.login=false;
           }
    })
    if(localStorage.getItem('username')!=null){
      this.login=true;
    }
  }

  logout(){
    console.log('Se supone que aprete logout')
    localStorage.clear();
    this.login=false;
    this.router.navigate(['/login']);
    this.http.logout().subscribe(
      data=>{
        },
      error=>{
        console.log(error);
      })

  }
  toggleDropdown() {
    let myNav = document.querySelector("#my-nav")
    let burger = document.querySelector("#burger")
    myNav!.classList.toggle("is-active")
    burger!.classList.toggle("is-active")
  }
}

<app-dashboard *ngIf="error"></app-dashboard>
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item pb-0 pt-0  mt-3" routerLink="">
      <h1 style="color:#00d1b2" class="has-text-weight-bold is-size-3 ">:</h1>
      <h1 style="color:#00d1b2" class="has-text-weight-bold is-size-4 ">D</h1>
      <h1 class=""> ietapp</h1>
    </a>
    <a id="burger" role="button" class="navbar-burger" (click)="toggleDropdown()" aria-label="menu"
       aria-expanded="false"
       data-target="my-nav">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="my-nav" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" routerLink="" (click)="toggleDropdown()" i18n>
        Home
      </a>

      <a class="navbar-item" routerLink="weight-history" *ngIf="login" (click)="toggleDropdown()" i18n>
        Weight-History
      </a>

      <!--      <div class="navbar-item has-dropdown is-hoverable" *ngIf="login">-->
      <!--        <a class="navbar-link">-->
      <!--          More-->
      <!--        </a>-->

      <!--        <div class="navbar-dropdown">-->
      <!--          <a class="navbar-item" routerLink="/role-user">-->
      <!--            Role-User-->
      <!--          </a>-->
      <!--          <a class="navbar-item" routerLink="/role-admin">-->
      <!--            Role-Admin-->
      <!--          </a>-->
      <!--          <hr class="navbar-divider">-->
      <!--        </div>-->
      <!--      </div>-->
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary" routerLink="/signup" *ngIf="!login" (click)="toggleDropdown()">
            <strong i18n>Sign up</strong>
          </a>
          <a class="button has-background-grey-lighter" routerLink="/login" *ngIf="!login" (click)="toggleDropdown()" i18n>
            Log in
          </a>
          <a class="button has-background-grey-lighter" (click)="logout()" *ngIf="login" (click)="toggleDropdown()" i18n>
            Logout
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>
<router-outlet></router-outlet>
<footer class="footer pt-5 pb-3 ">
  <div class="content has-text-centered ">
    <p>
      <strong>Dietapp</strong><a href="https://www.linkedin.com/in/alan-barrientos-041026239/" i18n> by Alan Barrientos.</a>
    </p>
    <p class="mt-0 mb-0 mr- pb-2 is-inline" i18n>Powered by:</p>
    <img style="height: 15px" src="./assets/angularlogo.png" class="is-inline mr-3 ml-3"/>
    <img style="height: 15px" src="./assets/springlogo.png" class="is-inline mr-3 ml-3"/>
    <img style="height: 15px" src="https://bulma.io/images/bulma-logo.png" class="is-inline mr-3 ml-3"/>
  </div>
</footer>
